<template>
	<div class="border-4 border-black">
		<p>
			ALL ABOUT US BLAH BLAH BLAH
			ALL ABOUT US BLAH BLAH BLAH
			ALL ABOUT US BLAH BLAH BLAH
			ALL ABOUT US BLAH BLAH BLAH
			ALL ABOUT US BLAH BLAH BLAH
			ALL ABOUT US BLAH BLAH BLAH
			ALL ABOUT US BLAH BLAH BLAH
			ALL ABOUT US BLAH BLAH BLAH
		</p>
	</div>
</template>